# Generated by Django 5.2.17 on 2026-08-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveRiskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_configuration_id', models.CharField(max_length=100, unique=True)),
                ('active_version', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveStrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(max_length=100, unique=True)),
                ('active_specification_version', models.CharField(max_length=100)),
                ('active_code_version', models.CharField(max_length=100)),
                ('active_configuration_version', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveUniverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universe_id', models.CharField(max_length=100, unique=True)),
                ('active_version', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskConfigurationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_configuration_id', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('max_intraday_loss', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_position_size', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_per_trade_risk', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['risk_configuration_id', 'created_at'], name='persistence_risk_co_b2ca95_idx')],
                'constraints': [models.UniqueConstraint(fields=('risk_configuration_id', 'version'), name='uniq_risk_configuration_version'), models.CheckConstraint(condition=models.Q(('max_intraday_loss__gt', 0)), name='risk_max_intraday_loss_positive'), models.CheckConstraint(condition=models.Q(('max_position_size__gt', 0)), name='risk_max_position_size_positive'), models.CheckConstraint(condition=models.Q(('max_per_trade_risk__gt', 0)), name='risk_max_per_trade_risk_positive')],
            },
        ),
        migrations.CreateModel(
            name='StrategyVersionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(max_length=100)),
                ('specification_version', models.CharField(max_length=100)),
                ('code_version', models.CharField(max_length=100)),
                ('configuration_version', models.CharField(max_length=100)),
                ('universe_version', models.CharField(max_length=100)),
                ('timeframe', models.CharField(max_length=10)),
                ('maturity_state', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['strategy_id', 'created_at'], name='persistence_strateg_25dd83_idx')],
                'constraints': [models.UniqueConstraint(fields=('strategy_id', 'specification_version', 'code_version', 'configuration_version'), name='uniq_strategy_version_identity')],
            },
        ),
        migrations.CreateModel(
            name='UniverseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universe_id', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], max_length=10)),
                ('members', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['universe_id', 'created_at'], name='persistence_univers_6d8784_idx')],
                'constraints': [models.UniqueConstraint(fields=('universe_id', 'version'), name='uniq_universe_version')],
            },
        ),
    ]
