# Generated by Django 5.2.17 on 2026-08-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0005_provider_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_safe', models.CharField(blank=True, default='', max_length=255)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LiveQuoteObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_symbol', models.CharField(max_length=32)),
                ('exchange', models.CharField(default='NSE', max_length=8)),
                ('last_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('source_timestamp', models.DateTimeField()),
                ('fetched_at', models.DateTimeField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['instrument_symbol', '-fetched_at'], name='persistence_instrum_5ae8e4_idx')],
            },
        ),
    ]
