# Generated by Django 5.2.17 on 2026-08-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0006_live_market_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedBarObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_symbol', models.CharField(max_length=32)),
                ('exchange', models.CharField(default='NSE', max_length=8)),
                ('timeframe', models.CharField(max_length=8)),
                ('interval_start', models.DateTimeField()),
                ('interval_end', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('status', models.CharField(choices=[('FORMING', 'FORMING'), ('CLOSED', 'CLOSED')], max_length=8)),
                ('observation_count', models.PositiveIntegerField()),
                ('data_source', models.CharField(max_length=32)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timeframe', '-interval_start'], name='persistence_timefra_728653_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument_symbol', 'timeframe', 'interval_start'), name='unique_bar_per_instrument_timeframe_interval')],
            },
        ),
    ]
