# Generated by Django 5.2.17 on 2026-08-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0007_aggregated_bars'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyConfigurationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(max_length=100)),
                ('specification_version', models.CharField(max_length=100)),
                ('code_version', models.CharField(max_length=100)),
                ('configuration_version', models.CharField(max_length=100)),
                ('parameter_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=150)),
            ],
            options={
                'indexes': [models.Index(fields=['strategy_id', 'created_at'], name='persistence_strateg_a5ceb3_idx')],
                'constraints': [models.UniqueConstraint(fields=('strategy_id', 'specification_version', 'code_version', 'configuration_version'), name='uniq_strategy_configuration_identity')],
            },
        ),
    ]
