# Generated by Django 5.2.17 on 2026-08-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0008_strategyconfigurationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyResearchStatusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('RESEARCH_ACTIVE', 'RESEARCH_ACTIVE'), ('RESEARCH_PAUSED', 'RESEARCH_PAUSED'), ('DISABLED', 'DISABLED')], default='RESEARCH_ACTIVE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BacktestResultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backtest_id', models.CharField(max_length=64, unique=True)),
                ('strategy_id', models.CharField(max_length=100)),
                ('result_payload', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=150)),
            ],
            options={
                'indexes': [models.Index(fields=['strategy_id', 'created_at'], name='persistence_strateg_7aee4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchlistRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner_username', models.CharField(max_length=150)),
                ('instrument_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner_username', 'name'), name='uniq_watchlist_per_owner')],
            },
        ),
    ]
