# Generated by Django 5.2.17 on 2026-08-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0009_strategyresearchstatusrecord_backtestresultrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillSwitchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperFundsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=4, max_digits=18)),
                ('utilized_margin', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperTradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=100, unique=True)),
                ('strategy_id', models.CharField(max_length=100)),
                ('instrument_id', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=10)),
                ('order_ids', models.JSONField(default=list)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('exit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costs', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PaperOrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('correlation_id', models.CharField(max_length=30)),
                ('instrument_id', models.CharField(max_length=100)),
                ('strategy_id', models.CharField(max_length=100)),
                ('side', models.CharField(max_length=10)),
                ('order_type', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('filled_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_history', models.JSONField(default=list)),
            ],
            options={
                'indexes': [models.Index(fields=['instrument_id', 'status'], name='persistence_instrum_2093fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaperPositionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(max_length=100, unique=True)),
                ('instrument_id', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('average_entry_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('unrealized_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='OPEN', max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['instrument_id', 'status'], name='persistence_instrum_4007c7_idx')],
            },
        ),
    ]
