# Generated by Django 5.2.17 on 2026-08-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0010_killswitchstate_paperfundsrecord_papertraderecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperorderrecord',
            name='signal_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
