# Generated by Django 5.2.17 on 2026-08-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0011_paperorderrecord_signal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLedgerRecord',
            fields=[
                ('communication_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('signal_id', models.CharField(max_length=100)),
                ('event_id', models.CharField(max_length=64)),
                ('channel', models.CharField(max_length=32)),
                ('provider', models.CharField(max_length=32)),
                ('destination_masked', models.CharField(blank=True, default='', max_length=100)),
                ('template_id', models.CharField(max_length=64)),
                ('template_version', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField()),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(max_length=32)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['signal_id', 'event_id', 'channel'], name='persistence_signal__77bbb4_idx')],
            },
        ),
    ]
