# Generated by Django 5.2.17 on 2026-08-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0012_communicationledgerrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpositionrecord',
            name='entry_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paperpositionrecord',
            name='exit_reason',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paperpositionrecord',
            name='highest_favorable_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='paperpositionrecord',
            name='lifecycle_status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='paperpositionrecord',
            name='remaining_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='paperpositionrecord',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='paperpositionrecord',
            name='strategy_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paperpositionrecord',
            name='strategy_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paperpositionrecord',
            name='target_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='paperpositionrecord',
            name='target_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='paperpositionrecord',
            name='target_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='paperpositionrecord',
            name='trailing_stop_distance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
