# Generated by Django 5.2.17 on 2026-08-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0014_emergencysquareoffevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EODRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eod_date', models.DateField(unique=True)),
                ('status', models.CharField(default='NOT_STARTED', max_length=32)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('positions_closed', models.PositiveIntegerField(default=0)),
                ('positions_failed', models.JSONField(default=list)),
                ('reconciliation_divergence_count', models.IntegerField(blank=True, null=True)),
                ('total_realized_pnl', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
