# Generated by Django 5.2.17 on 2026-08-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0015_eodrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.CharField(max_length=64, unique=True)),
                ('strategy_id', models.CharField(max_length=100)),
                ('instrument_id', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=16)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('timeframe', models.CharField(blank=True, default='', max_length=32)),
                ('signal_timestamp', models.DateTimeField()),
                ('risk_status', models.CharField(max_length=16)),
                ('risk_reason', models.CharField(blank=True, default='', max_length=1000)),
                ('order_status', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-signal_timestamp'],
                'indexes': [models.Index(fields=['-signal_timestamp'], name='persistence_signal__fa22ce_idx')],
            },
        ),
    ]
