# Generated by Django 5.2.17 on 2026-08-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0016_signalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('PARTIAL', 'PARTIAL'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='QUEUED', max_length=16)),
                ('phase', models.CharField(choices=[('QUEUED', 'QUEUED'), ('ANALYZING_DATA_COVERAGE', 'ANALYZING_DATA_COVERAGE'), ('FETCHING_HISTORICAL_DATA', 'FETCHING_HISTORICAL_DATA'), ('VALIDATING_DATA', 'VALIDATING_DATA'), ('PERSISTING_DATA', 'PERSISTING_DATA'), ('PREPARING_SCAN', 'PREPARING_SCAN'), ('SCANNING', 'SCANNING'), ('CALCULATING_RESULTS', 'CALCULATING_RESULTS'), ('FINALIZING', 'FINALIZING'), ('COMPLETED', 'COMPLETED'), ('PARTIAL', 'PARTIAL'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='QUEUED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('timeframe', models.CharField(max_length=8)),
                ('instrument_ids', models.JSONField(default=list)),
                ('strategy_id', models.CharField(max_length=100)),
                ('specification_version', models.CharField(max_length=32)),
                ('code_version', models.CharField(max_length=32)),
                ('configuration_version', models.CharField(max_length=32)),
                ('strategy_values', models.JSONField(default=dict)),
                ('cost_model_name', models.CharField(default='FLAT_PERCENTAGE', max_length=32)),
                ('initial_capital', models.DecimalField(decimal_places=4, max_digits=18)),
                ('position_sizing_mode', models.CharField(max_length=32)),
                ('position_size_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('brokerage_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('slippage_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('total_instruments', models.PositiveIntegerField(default=0)),
                ('completed_instruments', models.PositiveIntegerField(default=0)),
                ('total_bars', models.PositiveIntegerField(default=0)),
                ('scanned_bars', models.PositiveIntegerField(default=0)),
                ('signals_generated', models.PositiveIntegerField(default=0)),
                ('cache_hits', models.PositiveIntegerField(default=0)),
                ('cache_misses', models.PositiveIntegerField(default=0)),
                ('api_requests', models.PositiveIntegerField(default=0)),
                ('failed_instruments', models.JSONField(default=list)),
                ('result_backtest_ids', models.JSONField(default=dict)),
                ('error_message', models.CharField(blank=True, default='', max_length=2000)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_instrument', models.CharField(blank=True, default='', max_length=100)),
                ('current_strategy', models.CharField(blank=True, default='', max_length=100)),
                ('current_timestamp', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='persistence_created_92f9ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=8)),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(max_length=8)),
                ('bar_timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=20)),
                ('source', models.CharField(max_length=32)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['bar_timestamp'],
                'indexes': [models.Index(fields=['instrument_id', 'timeframe', 'bar_timestamp'], name='persistence_instrum_e84ad7_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument_id', 'timeframe', 'bar_timestamp'), name='uq_historical_bar_identity')],
            },
        ),
    ]
