# Generated by Django 5.2.17 on 2026-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0017_backtestrun_historicalbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrun',
            name='configuration_version',
            field=models.CharField(max_length=100),
        ),
    ]
