# Generated by Django 5.2.17 on 2026-08-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0018_alter_backtestrun_configuration_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('PARTIAL', 'PARTIAL'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='QUEUED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('timeframe', models.CharField(max_length=8)),
                ('instrument_ids', models.JSONField(default=list)),
                ('total_instruments', models.PositiveIntegerField(default=0)),
                ('completed_instruments', models.PositiveIntegerField(default=0)),
                ('bars_fetched', models.PositiveIntegerField(default=0)),
                ('bars_persisted', models.PositiveIntegerField(default=0)),
                ('cache_hits', models.PositiveIntegerField(default=0)),
                ('api_requests', models.PositiveIntegerField(default=0)),
                ('failed_instruments', models.JSONField(default=list)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_instrument', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='persistence_created_3497b8_idx')],
            },
        ),
    ]
