# Generated by Django 5.2.17 on 2026-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0019_marketdatasyncrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerRuntimeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='dhan', max_length=32, unique=True)),
                ('worker_state', models.CharField(default='STOPPED', max_length=32)),
                ('token_state', models.CharField(default='UNCONFIGURED', max_length=32)),
                ('watchdog_state', models.CharField(default='DISCONNECTED', max_length=32)),
                ('last_packet_at', models.DateTimeField(blank=True, null=True)),
                ('last_bar_at', models.DateTimeField(blank=True, null=True)),
                ('reconnect_count', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('subscribed_instrument_count', models.PositiveIntegerField(default=0)),
                ('last_error_safe', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
