# Generated by Django 5.2.17 on 2026-08-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0020_workerruntimestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='dhan', max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('timeframe', models.CharField(default='1m', max_length=8)),
                ('universe_mode', models.CharField(choices=[('ALL_CONFIGURED', 'ALL_CONFIGURED'), ('SELECTED', 'SELECTED'), ('WATCHLIST', 'WATCHLIST')], default='ALL_CONFIGURED', max_length=16)),
                ('selected_instrument_ids', models.JSONField(default=list)),
                ('selected_watchlist_name', models.CharField(blank=True, default='', max_length=200)),
                ('selected_strategy_ids', models.JSONField(default=list)),
                ('configuration_version', models.PositiveIntegerField(default=1)),
                ('requested_by', models.CharField(blank=True, default='', max_length=150)),
                ('requested_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='workerruntimestatus',
            name='effective_configuration_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerruntimestatus',
            name='effective_strategy_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='workerruntimestatus',
            name='effective_timeframe',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='workerruntimestatus',
            name='effective_universe_requested_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerruntimestatus',
            name='effective_universe_subscribed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
