# Generated by Django 5.2.17 on 2026-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0021_scannerconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradePlanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.CharField(db_index=True, max_length=100)),
                ('strategy_id', models.CharField(max_length=100)),
                ('code_version', models.CharField(max_length=32)),
                ('calculation_method', models.TextField(blank=True, default='')),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('target_1', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('target_2', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('target_3', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('trailing_stop_loss', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('generated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['signal_id'], name='persistence_signal__8b4eed_idx')],
            },
        ),
    ]
