# Generated by Django 5.2.17 on 2026-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0022_tradeplanrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerconfiguration',
            name='session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scannerconfiguration',
            name='session_stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
