# Generated by Django 5.2.17 on 2026-08-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0023_scannerconfiguration_session_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerScanProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='dhan', max_length=32, unique=True)),
                ('scan_id', models.CharField(blank=True, default='', max_length=64)),
                ('scan_started_at', models.DateTimeField(blank=True, null=True)),
                ('timeframe', models.CharField(blank=True, default='', max_length=8)),
                ('universe_total', models.PositiveIntegerField(default=0)),
                ('universe_processed', models.PositiveIntegerField(default=0)),
                ('current_instrument', models.CharField(blank=True, default='', max_length=100)),
                ('current_strategy', models.CharField(blank=True, default='', max_length=100)),
                ('strategies_total', models.PositiveIntegerField(default=0)),
                ('strategies_processed', models.PositiveIntegerField(default=0)),
                ('signals_found', models.PositiveIntegerField(default=0)),
                ('last_progress_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='IDLE', max_length=16)),
                ('last_error_safe', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
