# Generated by Django 5.2.17 on 2026-08-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0024_scannerscanprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalEvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.CharField(db_index=True, max_length=100)),
                ('strategy_id', models.CharField(max_length=100)),
                ('schema_version', models.CharField(max_length=16)),
                ('fields', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['signal_id'], name='persistence_signal__a0855d_idx')],
            },
        ),
    ]
