# Generated by Django 5.2.17 on 2026-08-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0025_signalevidencerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedbarobservation',
            name='volume',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='livequoteobservation',
            name='cumulative_volume',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
    ]
