# Generated by Django 5.2.17 on 2026-08-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0026_aggregatedbarobservation_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTradingSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='STOPPED', max_length=16)),
                ('strategy_id', models.CharField(max_length=100)),
                ('timeframe', models.CharField(default='5m', max_length=8)),
                ('instrument_ids', models.JSONField(default=list)),
                ('starting_capital', models.DecimalField(decimal_places=4, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('replay_date', models.DateField()),
                ('replay_cursor', models.PositiveIntegerField(default=0)),
                ('replay_total_steps', models.PositiveIntegerField(default=0)),
                ('playback_speed', models.PositiveIntegerField(default=1)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id'], name='persistence_session_f7662e_idx')],
            },
        ),
    ]
