# Generated by Django 5.2.17 on 2026-08-26 06:08

#
# Checkpoint 64.81 - CORRELATION TRACEABILITY. Three ADDITIVE columns,
# no AlterField, no RemoveField, and deliberately NO data migration.
#
# Every column is a blank-default CharField, so existing rows get `""` -
# which these fields DEFINE as "no traceable relationship recorded",
# exactly the meaning `PaperOrderRecord.signal_id` (Checkpoint 36) has
# carried for a blank value since it was introduced. No historical row's
# business meaning changes, and nothing is back-filled: nothing stored on
# an old record could PROVE which scan run or strategy version produced
# it, and guessing would fabricate exactly what this checkpoint exists to
# prevent.
#
# FIELDS DELIBERATELY *NOT* ADDED, after auditing what already exists
# (Phase 8's "do not duplicate" instruction):
#   - `PaperOrderRecord.signal_id`   - exists since Checkpoint 36.
#   - `ScannerScanProgress.scan_id`  - exists since Checkpoint 64.18.
#   - `strategy_version_identifier` on PaperOrder/PaperTrade - reachable
#     by join through `signal_id` to `SignalRecord`, so storing it twice
#     would duplicate reconstructable data AND would have required
#     changing the `OrderIntent` domain contract, whose exact field set
#     Checkpoint 64.31 freezes by test.
#
# Reverse is a plain column drop; only metadata is lost, never trading,
# P&L, or accounting values.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0030_option_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertraderecord',
            name='signal_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='scan_run_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='strategy_version_identifier',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
    ]
