# Generated by Django 5.2.17 on 2026-08-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0034_marketdataarchiveday_session_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerconfiguration',
            name='selected_notification_channels',
            field=models.JSONField(default=list),
        ),
    ]
