# Generated by Django 5.2.17 on 2026-09-01 11:29
#
# Checkpoint 67.9 Part 4: pure ADD — creates three brand-new,
# initially-empty tables (`MigrationRun`, `MigrationUnit`,
# `MigrationRow`) for the durable migration control-plane audit schema.
# No existing table (including `persistence_historicalbar`) is touched
# in any way: no column added/removed, no data read, no data written,
# no index/constraint on any existing table modified. Same
# forensic-evidence discipline as migrations 0037/0039: schema only,
# zero backfill, zero inference. Rolling back
# (`migrate persistence 0040`) simply drops these three new, still-
# empty tables.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0040_historicalbar_split_semantics_from_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_id', models.CharField(max_length=100)),
                ('row_id', models.BigIntegerField()),
                ('old_timestamp', models.DateTimeField()),
                ('new_timestamp', models.DateTimeField()),
                ('source_semantics', models.CharField(max_length=20)),
                ('proof_scope', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=40)),
            ],
            options={
                'indexes': [models.Index(fields=['migration_id', 'status'], name='mig_row_run_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('migration_id', 'row_id'), name='uq_migration_row_identity')],
            },
        ),
        migrations.CreateModel(
            name='MigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_id', models.CharField(max_length=100, unique=True)),
                ('migration_version', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('scope_fingerprint', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='mig_run_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='MigrationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_id', models.CharField(max_length=100)),
                ('unit_id', models.CharField(max_length=200)),
                ('instrument_id', models.CharField(max_length=100)),
                ('timeframe', models.CharField(max_length=8)),
                ('trading_date', models.DateField()),
                ('status', models.CharField(max_length=40)),
                ('old_row_count', models.IntegerField()),
                ('new_row_count', models.IntegerField()),
                ('old_scope_fingerprint', models.CharField(max_length=64)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['migration_id', 'status'], name='mig_unit_run_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('migration_id', 'unit_id'), name='uq_migration_unit_identity')],
            },
        ),
    ]
