# Generated by Django 5.2.17 on 2026-09-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0041_migrationrow_migrationrun_migrationunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerruntimestatus',
            name='owner_cmdline_safe',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='workerruntimestatus',
            name='owner_pid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerruntimestatus',
            name='owner_process_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
