/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit/risk-configuration/{configuration_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Every recorded activation attempt (activated/already_active/
         *     rejected) for one risk-configuration id, newest first.
         */
        get: operations["api_v1_audit_risk_configuration_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/strategy/{strategy_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Every recorded activation attempt for one strategy id, newest
         *     first. `version` on each event is the flattened
         *     `"{specification_version}:{code_version}:{configuration_version}"`
         *     identifier (see `DjangoStrategyVersionRepository.activate()`).
         */
        get: operations["api_v1_audit_strategy_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/universe/{universe_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every recorded activation attempt for one universe id, newest first. */
        get: operations["api_v1_audit_universe_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Authenticates a username/password pair and starts a session.
         *
         *     Brute-force protection: throttled to 5 requests/minute per client IP
         *     (`DEFAULT_THROTTLE_RATES["login"]`, settings/base.py) via DRF's
         *     cache-backed `ScopedRateThrottle` - see this view's `.cls.throttle_scope`
         *     assignment below (function-based views can't set a class attribute
         *     inline).
         *
         *     Login-CSRF protection (Checkpoint 12 - closes the gap Checkpoint 11
         *     deliberately deferred): DRF's `APIView.as_view()` wraps every view in
         *     Django's `csrf_exempt()` by default, delegating CSRF enforcement to
         *     `SessionAuthentication.enforce_csrf()` - which only runs once a
         *     session user is already resolved, so an anonymous login POST was
         *     never checked. This view's `.csrf_exempt` attribute is explicitly
         *     reset to `False` below (see after the function), re-enabling Django's
         *     real `CsrfViewMiddleware` for this one view - the same, real,
         *     framework-provided CSRF mechanism used everywhere else, not a
         *     hand-rolled scheme and never `@csrf_exempt`. This requires no
         *     frontend change: the frontend already calls `GET
         *     /api/v1/auth/session/` on load (which sets the `csrftoken` cookie via
         *     `get_token()`, see `session_view` below) before a user can submit the
         *     login form, and `client.ts` already attaches `X-CSRFToken` to every
         *     `POST`, login included.
         */
        post: operations["api_v1_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Ends the current session. Requires an authenticated session (so an
         *     anonymous POST is rejected by `IsAuthenticated`) and, because the
         *     caller is session-authenticated, DRF's `SessionAuthentication` enforces
         *     the CSRF header on this request - see docs/architecture/
         *     AUTHENTICATION_AUTHORIZATION.md's CSRF section.
         *
         *     Django's `logout()` flushes the session store entry itself (not just
         *     clearing the cookie), so the old session id is invalid server-side
         *     immediately - a leaked/cached cookie from before logout cannot be
         *     replayed.
         */
        post: operations["api_v1_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Reports the current authentication state. Deliberately returns
         *     `200` for anonymous callers too (`is_authenticated: false`), not
         *     `401` - this endpoint's entire purpose is "let the frontend safely
         *     ask, with no prior assumption," so treating "not logged in" as a
         *     request failure would force every caller to special-case it.
         *
         *     Also the frontend's mechanism for obtaining a CSRF cookie before its
         *     first state-changing request: `get_token(request)` guarantees Django's
         *     CSRF middleware sets the `csrftoken` cookie on this response, per
         *     Django's own documented pattern for SPA/AJAX clients that never
         *     render a `{% csrf_token %}` template tag.
         */
        get: operations["api_v1_auth_session_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/market-data/bars/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Checkpoint 24A: the most recently aggregated 1-minute bars,
         *     newest first - reads only already-persisted `AggregatedBarObservation`
         *     rows, NEVER triggers aggregation or a live broker call itself
         *     (Checkpoint 24A §11's "the API must not trigger broker calls").
         *     Optional `symbol` query parameter filters to one instrument.
         */
        get: operations["api_v1_config_market_data_bars_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/market-data/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Last-recorded live-market-data health - NEVER performs a live
         *     fetch itself (Checkpoint 23 §22's read-vs-refresh separation,
         *     matching Checkpoint 22's `provider_status` precedent exactly).
         */
        get: operations["api_v1_config_market_data_health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/market-data/quotes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The latest observed quote per configured instrument - reads
         *     already-persisted data only, never triggers a live fetch.
         */
        get: operations["api_v1_config_market_data_quotes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/market-data/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Performs exactly ONE live `POST /v2/marketfeed/quote` call
         *     against the configured observation universe (Checkpoint 23 §6/§7),
         *     persists the result, and returns the freshly-recomputed health
         *     snapshot. Rate-limited and debounced identically to Checkpoint 22's
         *     `dhan_test_connection` (same mechanism, a distinct throttle scope).
         *
         *     No order, position, or trading endpoint is called anywhere in this
         *     function (Checkpoint 23 §2's absolute safety boundary) - the only
         *     external call is `fetch_quotes()`, itself scoped to the documented
         *     read-only Market Quote endpoint.
         */
        post: operations["api_v1_config_market_data_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/market-data/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Current NSE cash-equity trading session - computed live, no
         *     persistence, no external call (Checkpoint 23 §8).
         */
        get: operations["api_v1_config_market_data_session_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/risk/{configuration_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_risk_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/risk/{configuration_id}/{version}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_risk_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/risk/{configuration_id}/{version}/activate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_risk_activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/risk/{configuration_id}/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_risk_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/settings/{provider}/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Returns the LAST RECORDED status - never performs a live check
         *     itself (Checkpoint 22 §22's explicit separation of "save settings"/
         *     "test connection"/"read status" as three distinct operations; also
         *     satisfies §23's "do not automatically test every provider every time
         *     the Settings page loads").
         */
        get: operations["api_v1_config_settings_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/settings/dhan/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_settings_dhan_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/settings/dhan/save/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_settings_dhan_save_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/settings/dhan/test/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_settings_dhan_test_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/settings/discord/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_settings_discord_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/settings/discord/save/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_settings_discord_save_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/settings/discord/test/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_settings_discord_test_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/settings/telegram/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_settings_telegram_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/settings/telegram/save/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_settings_telegram_save_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/settings/telegram/test/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_settings_telegram_test_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/strategy/{strategy_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_strategy_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/strategy/{strategy_id}/{specification_version}/{code_version}/{configuration_version}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_strategy_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/strategy/{strategy_id}/{specification_version}/{code_version}/{configuration_version}/activate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_strategy_activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/strategy/{strategy_id}/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_strategy_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/universe/{universe_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_universe_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/universe/{universe_id}/{version}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_universe_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/universe/{universe_id}/{version}/activate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_universe_activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/universe/{universe_id}/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_universe_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Liveness: is the process alive?
         *
         *     Must not depend on any external service (database, cache, broker) —
         *     a dependency outage must never make an otherwise-healthy process
         *     report itself as dead.
         */
        get: operations["healthz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Readiness: is this instance ready to serve its configured environment?
         *
         *     Validates infrastructure connectivity (database, cache) without ever
         *     exposing secrets, credentials, or connection strings in the response.
         */
        get: operations["readyz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Returns the application version from the single authoritative source
         *     (package metadata derived from pyproject.toml's version field) — never
         *     a second, independently hardcoded value.
         */
        get: operations["version_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /** @description Stable machine-readable error token, e.g. 'not_found', 'invalid_activation'. */
            error_code: string;
            /** @description Human-readable description, for logs/debugging. */
            message: string;
            /** @description Optional structured context (never a stack trace). */
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Response shape for one durable audit record. Read-only by
         *     construction - this serializer is never used to validate/deserialize
         *     a request body; there is no write endpoint for audit events.
         */
        AuditEventResponse: {
            actor: string;
            action: string;
            resource_type: string;
            resource_id: string;
            version: string;
            previous_version: string | null;
            outcome: components["schemas"]["OutcomeEnum"];
            /** Format: date-time */
            occurred_at: string;
            request_id: string;
        };
        /**
         * @description Checkpoint 24A. `status` is always present and explicit
         *     (FORMING/CLOSED, never implied) - the checkpoint's own requirement
         *     that a consumer can never mistake an in-progress bar for a closed
         *     one.
         */
        BarResponse: {
            symbol: string;
            exchange: string;
            timeframe: string;
            /** Format: date-time */
            interval_start: string;
            /** Format: date-time */
            interval_end: string;
            /** Format: decimal */
            open: string;
            /** Format: decimal */
            high: string;
            /** Format: decimal */
            low: string;
            /** Format: decimal */
            close: string;
            status: components["schemas"]["BarResponseStatusEnum"];
            observation_count: number;
            data_source: string;
        };
        /**
         * @description * `FORMING` - FORMING
         *     * `CLOSED` - CLOSED
         * @enum {string}
         */
        BarResponseStatusEnum: "FORMING" | "CLOSED";
        ConnectionStatusResponse: {
            provider: components["schemas"]["ProviderEnum"];
            status: components["schemas"]["ConnectionStatusResponseStatusEnum"];
            /** Format: date-time */
            last_checked_at: string | null;
            /** Format: date-time */
            last_success_at: string | null;
            /** Format: date-time */
            last_failure_at: string | null;
            failure_reason_safe: string;
            latency_ms: number | null;
        };
        /**
         * @description * `NOT_CONFIGURED` - NOT_CONFIGURED
         *     * `CONFIGURED` - CONFIGURED
         *     * `CONNECTING` - CONNECTING
         *     * `CONNECTED` - CONNECTED
         *     * `DISCONNECTED` - DISCONNECTED
         *     * `AUTHENTICATION_FAILED` - AUTHENTICATION_FAILED
         *     * `TOKEN_EXPIRED` - TOKEN_EXPIRED
         *     * `CONNECTION_ERROR` - CONNECTION_ERROR
         *     * `DISABLED` - DISABLED
         * @enum {string}
         */
        ConnectionStatusResponseStatusEnum: "NOT_CONFIGURED" | "CONFIGURED" | "CONNECTING" | "CONNECTED" | "DISCONNECTED" | "AUTHENTICATION_FAILED" | "TOKEN_EXPIRED" | "CONNECTION_ERROR" | "DISABLED";
        /**
         * @description Response shape for `GET /api/v1/auth/session/` and the successful
         *     result of `POST /api/v1/auth/login/`. Never includes a password,
         *     session key, or any other credential material - only what the
         *     frontend needs to answer "am I logged in, as whom, and what can I
         *     do.
         */
        CurrentUserResponse: {
            is_authenticated: boolean;
            username: string | null;
            capabilities: string[];
        };
        DhanSettingsResponse: {
            client_id_masked: string;
            client_id_source: components["schemas"]["ProviderConfigurationSourceEnum"];
            access_token_configured: boolean;
            access_token_source: components["schemas"]["ProviderConfigurationSourceEnum"];
            enabled: boolean;
            /** Format: date-time */
            updated_at: string | null;
            updated_by_username: string;
        };
        DhanSettingsSaveRequest: {
            client_id?: string;
            access_token?: string;
            enabled?: boolean;
        };
        DiscordSettingsResponse: {
            webhook_configured: boolean;
            webhook_source: components["schemas"]["ProviderConfigurationSourceEnum"];
            enabled: boolean;
            /** Format: date-time */
            updated_at: string | null;
            updated_by_username: string;
        };
        DiscordSettingsSaveRequest: {
            webhook_url?: string;
            enabled?: boolean;
        };
        HealthzResponse: {
            status: components["schemas"]["HealthzResponseStatusEnum"];
        };
        /**
         * @description * `alive` - alive
         * @enum {string}
         */
        HealthzResponseStatusEnum: "alive";
        /**
         * @description Request body for `POST /api/v1/auth/login/`. `password` is
         *     `write_only` purely for schema documentation purposes - the view
         *     never echoes any request field back in a response body regardless.
         */
        LoginRequest: {
            username: string;
            password: string;
        };
        MarketDataHealthResponse: {
            state: components["schemas"]["StateEnum"];
            /** Format: date-time */
            last_success_at: string | null;
            /** Format: date-time */
            last_failure_at: string | null;
            last_error_safe: string;
            /** Format: double */
            freshness_age_seconds: number | null;
            consecutive_failures: number;
            reconnect_count: number;
            subscription_active: boolean;
        };
        /**
         * @description * `activated` - activated
         *     * `already_active` - already_active
         *     * `rejected` - rejected
         * @enum {string}
         */
        OutcomeEnum: "activated" | "already_active" | "rejected";
        /**
         * @description * `DATABASE` - DATABASE
         *     * `ENVIRONMENT` - ENVIRONMENT
         *     * `UNCONFIGURED` - UNCONFIGURED
         * @enum {string}
         */
        ProviderConfigurationSourceEnum: "DATABASE" | "ENVIRONMENT" | "UNCONFIGURED";
        /**
         * @description * `dhan` - dhan
         *     * `telegram` - telegram
         *     * `discord` - discord
         * @enum {string}
         */
        ProviderEnum: "dhan" | "telegram" | "discord";
        QuoteResponse: {
            symbol: string;
            exchange: string;
            /** Format: decimal */
            last_price: string;
            /** Format: date-time */
            source_timestamp: string;
            /** Format: double */
            freshness_age_seconds: number;
            is_stale: boolean;
        };
        ReadyzResponse: {
            status: components["schemas"]["ReadyzResponseStatusEnum"];
            checks: {
                [key: string]: string;
            };
        };
        /**
         * @description * `ready` - ready
         *     * `not_ready` - not_ready
         * @enum {string}
         */
        ReadyzResponseStatusEnum: "ready" | "not_ready";
        /**
         * @description Response shape for a risk-configuration version. `is_active` is
         *     computed by the view (by comparing against the service's
         *     `get_active()` result), not stored on the domain/application record
         *     itself — "active" is a query-time relationship, not a property of
         *     the immutable version. See `RiskLimitsSerializer`'s docstring for why
         *     this serializer's generic parameter (and actual usage) differs from
         *     every sibling serializer in this codebase.
         */
        RiskConfigurationResponse: {
            risk_configuration_id: string;
            version: string;
            limits: components["schemas"]["RiskLimits"];
            /** Format: date-time */
            created_at: string;
            is_active: boolean;
        };
        /**
         * @description Mirrors `domain.risk.RiskLimits`'s three fields — same NUMERIC(14,2)
         *     precision as `infrastructure/persistence/models.py`'s
         *     `RiskConfigurationVersion`, so a value that round-trips through the
         *     API matches exactly what's stored.
         *
         *     Checkpoint 17.2: unlike every other serializer in this codebase
         *     (`serializers.Serializer[None]` — declared only for OpenAPI schema
         *     generation via `@extend_schema`, never actually instantiated with a
         *     real object), this one and `RiskConfigurationResponseSerializer`
         *     below ARE now actually used to serialize a real response
         *     (`infrastructure/api/risk_views.py`'s `_to_response_dict`) — the
         *     generic parameter reflects that: the real instance passed in is a
         *     plain `dict[str, object]` (nested dicts for `limits`), never `None`.
         *     This was the fix for the Decimal-serialized-as-float defect: DRF's
         *     `Response()` with a raw, un-serialized dict bypasses `DecimalField`/
         *     `COERCE_DECIMAL_TO_STRING` entirely and falls back to its own
         *     `JSONEncoder`, which converts `Decimal` to `float` — silently
         *     reintroducing binary floating-point into a financial-precision
         *     contract.
         */
        RiskLimits: {
            /** Format: decimal */
            max_intraday_loss: string;
            /** Format: decimal */
            max_position_size: string;
            /** Format: decimal */
            max_per_trade_risk: string;
        };
        SessionResponse: {
            /** Format: date */
            session_date: string;
            exchange: string;
            /** Format: date-time */
            market_open: string;
            /** Format: date-time */
            market_close: string;
            /** Format: date-time */
            square_off_deadline: string;
            status: components["schemas"]["SessionResponseStatusEnum"];
        };
        /**
         * @description * `PRE_OPEN` - PRE_OPEN
         *     * `OPEN` - OPEN
         *     * `CLOSED` - CLOSED
         * @enum {string}
         */
        SessionResponseStatusEnum: "PRE_OPEN" | "OPEN" | "CLOSED";
        /**
         * @description * `CONNECTED_FRESH` - CONNECTED_FRESH
         *     * `CONNECTED_STALE` - CONNECTED_STALE
         *     * `DISCONNECTED` - DISCONNECTED
         *     * `AUTHENTICATION_FAILED` - AUTHENTICATION_FAILED
         *     * `ERROR` - ERROR
         *     * `MARKET_CLOSED` - MARKET_CLOSED
         * @enum {string}
         */
        StateEnum: "CONNECTED_FRESH" | "CONNECTED_STALE" | "DISCONNECTED" | "AUTHENTICATION_FAILED" | "ERROR" | "MARKET_CLOSED";
        /**
         * @description Response shape for a strategy version. Identity is the 3-tuple
         *     (specification_version, code_version, configuration_version), matching
         *     `domain.strategy.StrategyVersion`'s own shape — `universe_version` may
         *     differ across otherwise-identical records. `is_active` is computed by
         *     the view, as in the sibling serializers.
         */
        StrategyVersionResponse: {
            strategy_id: string;
            specification_version: string;
            code_version: string;
            configuration_version: string;
            universe_version: string;
            timeframe: string;
            maturity_state: string;
            /** Format: date-time */
            created_at: string;
            is_active: boolean;
        };
        TelegramSettingsResponse: {
            channel_id_masked: string;
            channel_id_source: components["schemas"]["ProviderConfigurationSourceEnum"];
            bot_token_configured: boolean;
            bot_token_source: components["schemas"]["ProviderConfigurationSourceEnum"];
            enabled: boolean;
            /** Format: date-time */
            updated_at: string | null;
            updated_by_username: string;
        };
        TelegramSettingsSaveRequest: {
            bot_token?: string;
            channel_id?: string;
            enabled?: boolean;
        };
        /**
         * @description Mirrors `domain.universe.UniverseMember` — `instrument_id` is the
         *     domain-owned, broker-neutral identity (e.g. "NSE:RELIANCE"), never a
         *     broker token (Checkpoint 5).
         */
        UniverseMember: {
            instrument_id: string;
            status: string;
        };
        /**
         * @description Response shape for a universe version. `is_active` is computed by
         *     the view — see `RiskConfigurationResponseSerializer`'s docstring for
         *     the same rationale.
         */
        UniverseResponse: {
            universe_id: string;
            version: string;
            exchange: string;
            members: components["schemas"]["UniverseMember"][];
            /** Format: date-time */
            created_at: string;
            is_active: boolean;
        };
        VersionResponse: {
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_v1_audit_risk_configuration_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventResponse"][];
                };
            };
        };
    };
    api_v1_audit_strategy_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventResponse"][];
                };
            };
        };
    };
    api_v1_audit_universe_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventResponse"][];
                };
            };
        };
    };
    api_v1_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    api_v1_auth_session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    api_v1_config_market_data_bars_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarResponse"][];
                };
            };
        };
    };
    api_v1_config_market_data_health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketDataHealthResponse"];
                };
            };
        };
    };
    api_v1_config_market_data_quotes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"][];
                };
            };
        };
    };
    api_v1_config_market_data_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketDataHealthResponse"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_market_data_session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    api_v1_config_risk_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigurationResponse"][];
                };
            };
        };
    };
    api_v1_config_risk_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigurationResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_risk_activate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigurationResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_risk_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigurationResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_settings_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionStatusResponse"];
                };
            };
        };
    };
    api_v1_config_settings_dhan_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DhanSettingsResponse"];
                };
            };
        };
    };
    api_v1_config_settings_dhan_save_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DhanSettingsSaveRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DhanSettingsSaveRequest"];
                "multipart/form-data": components["schemas"]["DhanSettingsSaveRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DhanSettingsResponse"];
                };
            };
        };
    };
    api_v1_config_settings_dhan_test_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionStatusResponse"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_settings_discord_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscordSettingsResponse"];
                };
            };
        };
    };
    api_v1_config_settings_discord_save_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DiscordSettingsSaveRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DiscordSettingsSaveRequest"];
                "multipart/form-data": components["schemas"]["DiscordSettingsSaveRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscordSettingsResponse"];
                };
            };
        };
    };
    api_v1_config_settings_discord_test_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionStatusResponse"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_settings_telegram_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramSettingsResponse"];
                };
            };
        };
    };
    api_v1_config_settings_telegram_save_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TelegramSettingsSaveRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TelegramSettingsSaveRequest"];
                "multipart/form-data": components["schemas"]["TelegramSettingsSaveRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramSettingsResponse"];
                };
            };
        };
    };
    api_v1_config_settings_telegram_test_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionStatusResponse"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_strategy_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionResponse"][];
                };
            };
        };
    };
    api_v1_config_strategy_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code_version: string;
                configuration_version: string;
                specification_version: string;
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_strategy_activate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code_version: string;
                configuration_version: string;
                specification_version: string;
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_strategy_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_universe_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"][];
                };
            };
        };
    };
    api_v1_config_universe_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_universe_activate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_universe_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    healthz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    readyz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
        };
    };
    version_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
