/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Authenticates a username/password pair and starts a session.
         *
         *     Brute-force protection: throttled to 5 requests/minute per client IP
         *     (`DEFAULT_THROTTLE_RATES["login"]`, settings/base.py) via DRF's
         *     cache-backed `ScopedRateThrottle` - see this view's `.cls.throttle_scope`
         *     assignment below (function-based views can't set a class attribute
         *     inline).
         */
        post: operations["api_v1_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Ends the current session. Requires an authenticated session (so an
         *     anonymous POST is rejected by `IsAuthenticated`) and, because the
         *     caller is session-authenticated, DRF's `SessionAuthentication` enforces
         *     the CSRF header on this request - see docs/architecture/
         *     AUTHENTICATION_AUTHORIZATION.md's CSRF section.
         *
         *     Django's `logout()` flushes the session store entry itself (not just
         *     clearing the cookie), so the old session id is invalid server-side
         *     immediately - a leaked/cached cookie from before logout cannot be
         *     replayed.
         */
        post: operations["api_v1_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Reports the current authentication state. Deliberately returns
         *     `200` for anonymous callers too (`is_authenticated: false`), not
         *     `401` - this endpoint's entire purpose is "let the frontend safely
         *     ask, with no prior assumption," so treating "not logged in" as a
         *     request failure would force every caller to special-case it.
         *
         *     Also the frontend's mechanism for obtaining a CSRF cookie before its
         *     first state-changing request: `get_token(request)` guarantees Django's
         *     CSRF middleware sets the `csrftoken` cookie on this response, per
         *     Django's own documented pattern for SPA/AJAX clients that never
         *     render a `{% csrf_token %}` template tag.
         */
        get: operations["api_v1_auth_session_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/risk/{configuration_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_risk_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/risk/{configuration_id}/{version}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_risk_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/risk/{configuration_id}/{version}/activate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_risk_activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/risk/{configuration_id}/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_risk_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/strategy/{strategy_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_strategy_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/strategy/{strategy_id}/{specification_version}/{code_version}/{configuration_version}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_strategy_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/strategy/{strategy_id}/{specification_version}/{code_version}/{configuration_version}/activate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_strategy_activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/strategy/{strategy_id}/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_strategy_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/universe/{universe_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_universe_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/universe/{universe_id}/{version}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_universe_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/universe/{universe_id}/{version}/activate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_universe_activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/universe/{universe_id}/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_universe_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Liveness: is the process alive?
         *
         *     Must not depend on any external service (database, cache, broker) —
         *     a dependency outage must never make an otherwise-healthy process
         *     report itself as dead.
         */
        get: operations["healthz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Readiness: is this instance ready to serve its configured environment?
         *
         *     Validates infrastructure connectivity (database, cache) without ever
         *     exposing secrets, credentials, or connection strings in the response.
         */
        get: operations["readyz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Returns the application version from the single authoritative source
         *     (package metadata derived from pyproject.toml's version field) — never
         *     a second, independently hardcoded value.
         */
        get: operations["version_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /** @description Stable machine-readable error token, e.g. 'not_found', 'invalid_activation'. */
            error_code: string;
            /** @description Human-readable description, for logs/debugging. */
            message: string;
            /** @description Optional structured context (never a stack trace). */
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Response shape for `GET /api/v1/auth/session/` and the successful
         *     result of `POST /api/v1/auth/login/`. Never includes a password,
         *     session key, or any other credential material - only what the
         *     frontend needs to answer "am I logged in, as whom, and what can I
         *     do.
         */
        CurrentUserResponse: {
            is_authenticated: boolean;
            username: string | null;
            capabilities: string[];
        };
        HealthzResponse: {
            status: components["schemas"]["HealthzResponseStatusEnum"];
        };
        /**
         * @description * `alive` - alive
         * @enum {string}
         */
        HealthzResponseStatusEnum: "alive";
        /**
         * @description Request body for `POST /api/v1/auth/login/`. `password` is
         *     `write_only` purely for schema documentation purposes - the view
         *     never echoes any request field back in a response body regardless.
         */
        LoginRequest: {
            username: string;
            password: string;
        };
        ReadyzResponse: {
            status: components["schemas"]["ReadyzResponseStatusEnum"];
            checks: {
                [key: string]: string;
            };
        };
        /**
         * @description * `ready` - ready
         *     * `not_ready` - not_ready
         * @enum {string}
         */
        ReadyzResponseStatusEnum: "ready" | "not_ready";
        /**
         * @description Response shape for a risk-configuration version. `is_active` is
         *     computed by the view (by comparing against the service's
         *     `get_active()` result), not stored on the domain/application record
         *     itself — "active" is a query-time relationship, not a property of
         *     the immutable version.
         */
        RiskConfigurationResponse: {
            risk_configuration_id: string;
            version: string;
            limits: components["schemas"]["RiskLimits"];
            /** Format: date-time */
            created_at: string;
            is_active: boolean;
        };
        /**
         * @description Mirrors `domain.risk.RiskLimits`'s three fields — same NUMERIC(14,2)
         *     precision as `infrastructure/persistence/models.py`'s
         *     `RiskConfigurationVersion`, so a value that round-trips through the
         *     API matches exactly what's stored.
         */
        RiskLimits: {
            /** Format: decimal */
            max_intraday_loss: string;
            /** Format: decimal */
            max_position_size: string;
            /** Format: decimal */
            max_per_trade_risk: string;
        };
        /**
         * @description Response shape for a strategy version. Identity is the 3-tuple
         *     (specification_version, code_version, configuration_version), matching
         *     `domain.strategy.StrategyVersion`'s own shape — `universe_version` may
         *     differ across otherwise-identical records. `is_active` is computed by
         *     the view, as in the sibling serializers.
         */
        StrategyVersionResponse: {
            strategy_id: string;
            specification_version: string;
            code_version: string;
            configuration_version: string;
            universe_version: string;
            timeframe: string;
            maturity_state: string;
            /** Format: date-time */
            created_at: string;
            is_active: boolean;
        };
        /**
         * @description Mirrors `domain.universe.UniverseMember` — `instrument_id` is the
         *     domain-owned, broker-neutral identity (e.g. "NSE:RELIANCE"), never a
         *     broker token (Checkpoint 5).
         */
        UniverseMember: {
            instrument_id: string;
            status: string;
        };
        /**
         * @description Response shape for a universe version. `is_active` is computed by
         *     the view — see `RiskConfigurationResponseSerializer`'s docstring for
         *     the same rationale.
         */
        UniverseResponse: {
            universe_id: string;
            version: string;
            exchange: string;
            members: components["schemas"]["UniverseMember"][];
            /** Format: date-time */
            created_at: string;
            is_active: boolean;
        };
        VersionResponse: {
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_v1_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    api_v1_auth_session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    api_v1_config_risk_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigurationResponse"][];
                };
            };
        };
    };
    api_v1_config_risk_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigurationResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_risk_activate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigurationResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_risk_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigurationResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_strategy_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionResponse"][];
                };
            };
        };
    };
    api_v1_config_strategy_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code_version: string;
                configuration_version: string;
                specification_version: string;
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_strategy_activate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code_version: string;
                configuration_version: string;
                specification_version: string;
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_strategy_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_universe_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"][];
                };
            };
        };
    };
    api_v1_config_universe_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_universe_activate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_universe_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    healthz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    readyz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
        };
    };
    version_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
