/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/config/risk/{configuration_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_risk_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/risk/{configuration_id}/{version}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_risk_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/risk/{configuration_id}/{version}/activate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_risk_activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/risk/{configuration_id}/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_risk_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/strategy/{strategy_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_strategy_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/strategy/{strategy_id}/{specification_version}/{code_version}/{configuration_version}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_strategy_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/strategy/{strategy_id}/{specification_version}/{code_version}/{configuration_version}/activate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_strategy_activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/strategy/{strategy_id}/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_strategy_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/universe/{universe_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_universe_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/universe/{universe_id}/{version}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_universe_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/universe/{universe_id}/{version}/activate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_config_universe_activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/universe/{universe_id}/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_config_universe_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Liveness: is the process alive?
         *
         *     Must not depend on any external service (database, cache, broker) —
         *     a dependency outage must never make an otherwise-healthy process
         *     report itself as dead.
         */
        get: operations["healthz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Readiness: is this instance ready to serve its configured environment?
         *
         *     Validates infrastructure connectivity (database, cache) without ever
         *     exposing secrets, credentials, or connection strings in the response.
         */
        get: operations["readyz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Returns the application version from the single authoritative source
         *     (package metadata derived from pyproject.toml's version field) — never
         *     a second, independently hardcoded value.
         */
        get: operations["version_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /** @description Stable machine-readable error token, e.g. 'not_found', 'invalid_activation'. */
            error_code: string;
            /** @description Human-readable description, for logs/debugging. */
            message: string;
            /** @description Optional structured context (never a stack trace). */
            details?: {
                [key: string]: unknown;
            };
        };
        HealthzResponse: {
            status: components["schemas"]["HealthzResponseStatusEnum"];
        };
        /**
         * @description * `alive` - alive
         * @enum {string}
         */
        HealthzResponseStatusEnum: "alive";
        ReadyzResponse: {
            status: components["schemas"]["ReadyzResponseStatusEnum"];
            checks: {
                [key: string]: string;
            };
        };
        /**
         * @description * `ready` - ready
         *     * `not_ready` - not_ready
         * @enum {string}
         */
        ReadyzResponseStatusEnum: "ready" | "not_ready";
        /**
         * @description Response shape for a risk-configuration version. `is_active` is
         *     computed by the view (by comparing against the service's
         *     `get_active()` result), not stored on the domain/application record
         *     itself — "active" is a query-time relationship, not a property of
         *     the immutable version.
         */
        RiskConfigurationResponse: {
            risk_configuration_id: string;
            version: string;
            limits: components["schemas"]["RiskLimits"];
            /** Format: date-time */
            created_at: string;
            is_active: boolean;
        };
        /**
         * @description Mirrors `domain.risk.RiskLimits`'s three fields — same NUMERIC(14,2)
         *     precision as `infrastructure/persistence/models.py`'s
         *     `RiskConfigurationVersion`, so a value that round-trips through the
         *     API matches exactly what's stored.
         */
        RiskLimits: {
            /** Format: decimal */
            max_intraday_loss: string;
            /** Format: decimal */
            max_position_size: string;
            /** Format: decimal */
            max_per_trade_risk: string;
        };
        /**
         * @description Response shape for a strategy version. Identity is the 3-tuple
         *     (specification_version, code_version, configuration_version), matching
         *     `domain.strategy.StrategyVersion`'s own shape — `universe_version` may
         *     differ across otherwise-identical records. `is_active` is computed by
         *     the view, as in the sibling serializers.
         */
        StrategyVersionResponse: {
            strategy_id: string;
            specification_version: string;
            code_version: string;
            configuration_version: string;
            universe_version: string;
            timeframe: string;
            maturity_state: string;
            /** Format: date-time */
            created_at: string;
            is_active: boolean;
        };
        /**
         * @description Mirrors `domain.universe.UniverseMember` — `instrument_id` is the
         *     domain-owned, broker-neutral identity (e.g. "NSE:RELIANCE"), never a
         *     broker token (Checkpoint 5).
         */
        UniverseMember: {
            instrument_id: string;
            status: string;
        };
        /**
         * @description Response shape for a universe version. `is_active` is computed by
         *     the view — see `RiskConfigurationResponseSerializer`'s docstring for
         *     the same rationale.
         */
        UniverseResponse: {
            universe_id: string;
            version: string;
            exchange: string;
            members: components["schemas"]["UniverseMember"][];
            /** Format: date-time */
            created_at: string;
            is_active: boolean;
        };
        VersionResponse: {
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_v1_config_risk_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigurationResponse"][];
                };
            };
        };
    };
    api_v1_config_risk_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigurationResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_risk_activate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigurationResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_risk_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigurationResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_strategy_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionResponse"][];
                };
            };
        };
    };
    api_v1_config_strategy_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code_version: string;
                configuration_version: string;
                specification_version: string;
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_strategy_activate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code_version: string;
                configuration_version: string;
                specification_version: string;
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_strategy_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_universe_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"][];
                };
            };
        };
    };
    api_v1_config_universe_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_universe_activate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    api_v1_config_universe_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    healthz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    readyz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
        };
    };
    version_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
