# tests/validation/fixtures.py
#
# Checkpoint 30 Part 4/5/13: frozen, deterministic validation datasets -
# both the small "micro" fixture and the larger "extended" fixture used
# as this checkpoint's stand-in for a real historical NSE dataset.
#
# HONEST LIMITATION (Part 5, recorded here and in
# docs/research/BACKTEST_REFERENCE_VALIDATION.md): this environment has
# no verified Dhan credential and no licensed real-market historical
# data source. A genuinely real NSE historical period could NOT be
# obtained this checkpoint. The "extended" dataset below is therefore
# still SYNTHETIC - generated by a fixed, seeded, documented algorithm
# (never real market prices) - but is FROZEN exactly like a real
# dataset would be: assigned a dataset ID, a SHA-256 checksum of its own
# bar data, and treated as immutable for the rest of this checkpoint's
# reproducibility chain. This is not claimed to be equivalent to real-
# market validation - see the report's own "Dataset Identity" section
# for the explicit distinction.
from __future__ import annotations

import hashlib
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from decimal import Decimal

from tests.validation.reference_engine import ReferenceBar


@dataclass(frozen=True)
class FrozenDataset:
    dataset_id: str
    source: str
    retrieval_timestamp: str
    instrument_id: str
    exchange: str
    timeframe: str
    start: str
    end: str
    bar_count: int
    checksum: str
    bars: tuple[ReferenceBar, ...]


def _checksum(bars: tuple[ReferenceBar, ...]) -> str:
    payload = "|".join(f"{b.timestamp}:{b.open}:{b.high}:{b.low}:{b.close}" for b in bars)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _build(
    dataset_id: str, instrument_id: str, prices: list[tuple[str, str, str, str]]
) -> FrozenDataset:
    base = datetime(2026, 1, 5, 3, 45, tzinfo=UTC)
    bars = tuple(
        ReferenceBar(
            timestamp=(base + timedelta(minutes=i)).isoformat(),
            open=Decimal(o),
            high=Decimal(h),
            low=Decimal(low),
            close=Decimal(c),
        )
        for i, (o, h, low, c) in enumerate(prices)
    )
    return FrozenDataset(
        dataset_id=dataset_id,
        source="SYNTHETIC - fixed, seeded, documented algorithm (see fixtures.py) - "
        "NOT real market data (no licensed historical NSE data source was "
        "available in this environment - see Checkpoint 30's own honest "
        "limitation note)",
        retrieval_timestamp="2026-08-14T00:00:00Z",
        instrument_id=instrument_id,
        exchange="NSE",
        timeframe="1m",
        start=bars[0].timestamp,
        end=bars[-1].timestamp,
        bar_count=len(bars),
        checksum=_checksum(bars),
        bars=bars,
    )


def micro_fixture() -> FrozenDataset:
    """Part 4: a small (30-bar), hand-designed synthetic dataset with a
    controlled trend structure - flat warm-up, a clean uptrend (forces a
    BULLISH crossover), a sharp reversal (forces a BEARISH crossover),
    then flat into end-of-data (forces an end_of_data close) - so every
    trade-closing reason path is exercised at least once."""
    prices: list[tuple[str, str, str, str]] = []
    # bars 0-7: flat at 100 (EMA warm-up, lookback=6 needs 6 closes)
    for _ in range(8):
        prices.append(("99", "101", "98", "100"))
    # bars 8-17: clean uptrend 101..110
    for i in range(10):
        p = 101 + i
        prices.append((str(p - 1), str(p + 1), str(p - 2), str(p)))
    # bars 18-24: sharp reversal downtrend 108..102
    for i in range(7):
        p = 108 - i
        prices.append((str(p + 1), str(p + 2), str(p - 1), str(p)))
    # bars 25-29: flat tail at 102 into end-of-data
    for _ in range(5):
        prices.append(("101", "103", "100", "102"))
    return _build("MICRO-EMA-CROSSOVER-V1", "NSE:VALIDATION01", prices)


def extended_fixture() -> FrozenDataset:
    """Part 5: a larger (150-bar) frozen synthetic dataset, generated by
    a fixed seeded pseudo-random walk (never real market data - see this
    module's own header). Deterministic: same seed, same output, every
    time."""
    import random

    rng = random.Random(20260814)  # noqa: S311 - deterministic test fixture, not security-sensitive
    prices: list[tuple[str, str, str, str]] = []
    price = 250
    for _ in range(150):
        price += rng.choice([-3, -2, -1, -1, 1, 1, 2, 3])
        price = max(price, 50)
        o, c = price - 1, price
        h, low = price + rng.choice([1, 2, 3]), price - rng.choice([1, 2, 3])
        prices.append((str(o), str(h), str(low), str(c)))
    return _build("EXTENDED-EMA-CROSSOVER-V1", "NSE:VALIDATION02", prices)


def second_instrument_for_portfolio() -> FrozenDataset:
    """A second, independent series for Part 10's portfolio validation -
    same length as the micro fixture, different trend shape, so the two
    instruments' signals do not trivially coincide."""
    prices: list[tuple[str, str, str, str]] = []
    for _ in range(8):
        prices.append(("199", "201", "198", "200"))
    for i in range(10):
        p = 201 - i  # downtrend this time
        prices.append((str(p + 1), str(p + 2), str(p - 1), str(p)))
    for i in range(7):
        p = 191 + i  # reversal upward
        prices.append((str(p - 1), str(p + 1), str(p - 2), str(p)))
    for _ in range(5):
        prices.append(("197", "199", "196", "198"))
    return _build("MICRO-EMA-CROSSOVER-INSTRUMENT-B-V1", "NSE:VALIDATION03", prices)
