# tests/unit/signal_intelligence/feature_engine/test_ema.py
#
# Unit tests for the Checkpoint 16 EMA computation - pure Python, no
# database, no Django, runs unconditionally.
from __future__ import annotations

from datetime import UTC, datetime, timedelta
from decimal import Decimal

import pytest
from hypothesis import given
from hypothesis import strategies as st

from intraday.domain.instrument.contracts import make_instrument_id
from intraday.domain.market_data.contracts import Bar
from intraday.domain.market_data.quality import DuplicateBarTimestampError, OutOfOrderBarError
from intraday.domain.shared_kernel.contracts import Exchange, InstrumentId, Timeframe
from intraday.signal_intelligence.feature_engine.definitions import (
    ExponentialMovingAverageDefinition,
)
from intraday.signal_intelligence.feature_engine.ema import compute_exponential_moving_average
from intraday.signal_intelligence.feature_engine.errors import (
    InvalidLookbackError,
    MixedInstrumentSeriesError,
    MixedTimeframeSeriesError,
)

RELIANCE = make_instrument_id(Exchange.NSE, "RELIANCE")
TCS = make_instrument_id(Exchange.NSE, "TCS")
START = datetime(2026, 1, 1, 3, 50, tzinfo=UTC)


def _bar(
    close: str,
    *,
    offset_minutes: int = 0,
    instrument_id: InstrumentId = RELIANCE,
    timeframe: Timeframe = Timeframe.FIVE_MINUTE,
) -> Bar:
    price = Decimal(close)
    return Bar(
        instrument_id=instrument_id,
        timeframe=timeframe,
        timestamp=START + timedelta(minutes=5 * offset_minutes),
        open=price,
        high=price + Decimal("1"),
        low=price - Decimal("1"),
        close=price,
        volume=Decimal("1000"),
    )


def _series(*closes: str) -> tuple[Bar, ...]:
    return tuple(_bar(close, offset_minutes=i) for i, close in enumerate(closes))


# ---------------------------------------------------------------------------
# Feature identity
# ---------------------------------------------------------------------------


def test_ema_5_and_ema_10_have_distinct_identity() -> None:
    ema5 = ExponentialMovingAverageDefinition(lookback=5)
    ema10 = ExponentialMovingAverageDefinition(lookback=10)
    assert ema5.feature_name != ema10.feature_name
    assert ema5.feature_name == "ema_5"
    assert ema10.feature_name == "ema_10"


def test_same_definition_produces_equal_identity() -> None:
    a = ExponentialMovingAverageDefinition(lookback=20)
    b = ExponentialMovingAverageDefinition(lookback=20)
    assert a == b
    assert a.feature_name == b.feature_name
    assert a.feature_version == b.feature_version


@pytest.mark.parametrize("invalid_lookback", [0, -1, -5])
def test_invalid_lookback_rejected(invalid_lookback: int) -> None:
    with pytest.raises(InvalidLookbackError):
        ExponentialMovingAverageDefinition(lookback=invalid_lookback)


def test_non_integer_lookback_rejected() -> None:
    with pytest.raises(InvalidLookbackError):
        ExponentialMovingAverageDefinition(lookback=5.5)  # type: ignore[arg-type]


def test_bool_lookback_rejected() -> None:
    with pytest.raises(InvalidLookbackError):
        ExponentialMovingAverageDefinition(lookback=True)  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# Calculation - independently hand-derived test vector (Checkpoint 16 §17)
#
#   period N = 3, alpha = 2 / (3 + 1) = 0.5, one_minus_alpha = 0.5
#   closes: 10, 20, 30, 40, 50
#   seed (mean of first 3 closes): (10 + 20 + 30) / 3 = 20   -> at bar index 2
#   EMA_4 = 0.5 * 40 + 0.5 * 20 = 20 + 10 = 30
#   EMA_5 = 0.5 * 50 + 0.5 * 30 = 25 + 15 = 40
#   expected EMA(3) series: 20, 30, 40
#
# Derived independently of the implementation under test (by hand, per the
# documented seed/recurrence rule) - not generated by calling
# compute_exponential_moving_average itself.
# ---------------------------------------------------------------------------


def test_known_3_period_ema_manually_derived_vector() -> None:
    bars = _series("10", "20", "30", "40", "50")
    definition = ExponentialMovingAverageDefinition(lookback=3)

    values = compute_exponential_moving_average(definition, bars)

    assert [v.value for v in values] == [Decimal("20"), Decimal("30"), Decimal("40")]


def test_decimal_precision_preserved_not_float() -> None:
    bars = _series("100.01", "100.02", "100.03")
    definition = ExponentialMovingAverageDefinition(lookback=3)

    values = compute_exponential_moving_average(definition, bars)

    assert len(values) == 1
    assert isinstance(values[0].value, Decimal)
    assert values[0].value == Decimal("100.02")


def test_alpha_calculation_matches_canonical_formula() -> None:
    """alpha = 2 / (N + 1); for N=4, alpha=0.4, one_minus_alpha=0.6 - a
    second, independently hand-derived vector distinct from the N=3 one."""
    bars = _series("10", "10", "10", "10", "20")  # seed=10, then one recursive step
    definition = ExponentialMovingAverageDefinition(lookback=4)

    values = compute_exponential_moving_average(definition, bars)

    # seed = mean(10,10,10,10) = 10
    # EMA_5 = 0.4*20 + 0.6*10 = 8 + 6 = 14
    assert values[0].value == Decimal("10")
    assert values[1].value == Decimal("14")


def test_recurrence_relationship_holds_for_every_post_seed_value() -> None:
    bars = _series("100", "102", "98", "105", "110", "95", "120")
    definition = ExponentialMovingAverageDefinition(lookback=3)
    alpha = Decimal(2) / Decimal(4)

    values = compute_exponential_moving_average(definition, bars)

    post_seed_bars = bars[definition.lookback :]
    for previous, current, bar in zip(values, values[1:], post_seed_bars, strict=False):
        assert current.value == alpha * bar.close + (Decimal(1) - alpha) * previous.value


def test_lookback_one_ema_equals_raw_close_series() -> None:
    """N=1 -> alpha = 2/2 = 1, one_minus_alpha = 0, so EMA_t = close_t for
    every bar, starting at the first bar (seed = mean of the first 1
    close = that close). Mathematically correct behavior, verified
    explicitly rather than special-cased in the implementation."""
    bars = _series("100", "105", "95", "110")
    definition = ExponentialMovingAverageDefinition(lookback=1)

    values = compute_exponential_moving_average(definition, bars)

    assert [v.value for v in values] == [
        Decimal("100"),
        Decimal("105"),
        Decimal("95"),
        Decimal("110"),
    ]


def test_lookback_two() -> None:
    # alpha = 2/3
    bars = _series("9", "12")
    definition = ExponentialMovingAverageDefinition(lookback=2)

    values = compute_exponential_moving_average(definition, bars)

    assert values[0].value == Decimal("10.5")  # seed = mean(9,12)


def test_output_is_chronologically_ordered() -> None:
    bars = _series("100", "101", "102", "103", "104")
    definition = ExponentialMovingAverageDefinition(lookback=2)

    values = compute_exponential_moving_average(definition, bars)

    timestamps = [v.timestamp for v in values]
    assert timestamps == sorted(timestamps)


# ---------------------------------------------------------------------------
# Warm-up / seed
# ---------------------------------------------------------------------------


def test_zero_bars_produces_no_values() -> None:
    definition = ExponentialMovingAverageDefinition(lookback=5)
    assert compute_exponential_moving_average(definition, ()) == ()


def test_fewer_than_n_bars_produces_no_values() -> None:
    bars = _series("100", "101", "102", "103")  # 4 bars, lookback 5
    definition = ExponentialMovingAverageDefinition(lookback=5)
    assert compute_exponential_moving_average(definition, bars) == ()


def test_exactly_n_bars_produces_exactly_one_seed_value() -> None:
    bars = _series("100", "102", "104", "106", "108")  # 5 bars, lookback 5
    definition = ExponentialMovingAverageDefinition(lookback=5)

    values = compute_exponential_moving_average(definition, bars)

    assert len(values) == 1
    assert values[0].value == Decimal("104")  # mean of all 5


def test_n_plus_one_bars_produces_exactly_two_values() -> None:
    bars = _series("100", "102", "104", "106", "108", "110")  # 6 bars, lookback 5
    definition = ExponentialMovingAverageDefinition(lookback=5)

    values = compute_exponential_moving_average(definition, bars)

    assert len(values) == 2


def test_first_valid_timestamp_is_the_nth_bar_not_the_first() -> None:
    bars = _series("10", "20", "30", "40")
    definition = ExponentialMovingAverageDefinition(lookback=3)

    values = compute_exponential_moving_average(definition, bars)

    assert values[0].timestamp == bars[2].timestamp  # the 3rd (Nth) bar, not bars[0]


def test_seed_agrees_with_documented_convention_mean_of_first_n_closes() -> None:
    bars = _series("5", "7", "9", "11")
    definition = ExponentialMovingAverageDefinition(lookback=4)

    values = compute_exponential_moving_average(definition, bars)

    assert values[0].value == (Decimal("5") + Decimal("7") + Decimal("9") + Decimal("11")) / 4


# ---------------------------------------------------------------------------
# Look-ahead safety
# ---------------------------------------------------------------------------


def test_future_bar_does_not_influence_earlier_output() -> None:
    short_series = _series("100", "102", "104")
    longer_series = short_series + (_bar("999", offset_minutes=3),)
    definition = ExponentialMovingAverageDefinition(lookback=3)

    short_values = compute_exponential_moving_average(definition, short_series)
    longer_values = compute_exponential_moving_average(definition, longer_series)

    assert short_values[0] == longer_values[0]


def test_modifying_a_future_bar_does_not_change_earlier_ema_values() -> None:
    definition = ExponentialMovingAverageDefinition(lookback=2)
    base = _series("100", "102", "104")
    variant_a = base + (_bar("200", offset_minutes=3),)
    variant_b = base + (_bar("9999", offset_minutes=3),)

    values_a = compute_exponential_moving_average(definition, variant_a)
    values_b = compute_exponential_moving_average(definition, variant_b)

    assert values_a[:-1] == values_b[:-1]


@given(
    closes=st.lists(
        st.decimals(min_value="10", max_value="10000", places=2, allow_nan=False),
        min_size=2,
        max_size=25,
    ),
    lookback=st.integers(min_value=1, max_value=10),
)
def test_no_output_uses_future_observations(closes: list[Decimal], lookback: int) -> None:
    full_bars = tuple(_bar(str(close), offset_minutes=i) for i, close in enumerate(closes))
    prefix_bars = full_bars[:-1]
    definition = ExponentialMovingAverageDefinition(lookback=lookback)

    full_values = compute_exponential_moving_average(definition, full_bars)
    prefix_values = compute_exponential_moving_average(definition, prefix_bars)

    assert prefix_values == full_values[: len(prefix_values)]


# ---------------------------------------------------------------------------
# Instrument / timeframe integrity
# ---------------------------------------------------------------------------


def test_bars_from_different_instruments_rejected() -> None:
    bars = (
        _bar("100", offset_minutes=0, instrument_id=RELIANCE),
        _bar("101", offset_minutes=1, instrument_id=TCS),
    )
    definition = ExponentialMovingAverageDefinition(lookback=2)

    with pytest.raises(MixedInstrumentSeriesError):
        compute_exponential_moving_average(definition, bars)


def test_feature_output_retains_correct_instrument_identity() -> None:
    bars = _series("100", "102", "104")
    definition = ExponentialMovingAverageDefinition(lookback=3)

    values = compute_exponential_moving_average(definition, bars)

    assert values[0].instrument_id == RELIANCE


def test_timeframe_is_retained_on_output() -> None:
    bars = _series("100", "102", "104")
    definition = ExponentialMovingAverageDefinition(lookback=3)

    values = compute_exponential_moving_average(definition, bars)

    assert values[0].timeframe == Timeframe.FIVE_MINUTE


def test_mixed_timeframe_input_rejected() -> None:
    bars = (
        _bar("100", offset_minutes=0, timeframe=Timeframe.FIVE_MINUTE),
        _bar("101", offset_minutes=1, timeframe=Timeframe.ONE_MINUTE),
    )
    definition = ExponentialMovingAverageDefinition(lookback=2)

    with pytest.raises(MixedTimeframeSeriesError):
        compute_exponential_moving_average(definition, bars)


def test_duplicate_bar_timestamps_rejected() -> None:
    duplicate = _bar("100", offset_minutes=0)
    bars = (duplicate, duplicate)
    definition = ExponentialMovingAverageDefinition(lookback=2)

    with pytest.raises(DuplicateBarTimestampError):
        compute_exponential_moving_average(definition, bars)


def test_out_of_order_bars_rejected() -> None:
    bars = (_bar("100", offset_minutes=1), _bar("101", offset_minutes=0))
    definition = ExponentialMovingAverageDefinition(lookback=2)

    with pytest.raises(OutOfOrderBarError):
        compute_exponential_moving_average(definition, bars)


# ---------------------------------------------------------------------------
# Determinism
# ---------------------------------------------------------------------------


def test_same_input_produces_identical_output() -> None:
    bars = _series("100", "102", "104", "106", "108")
    definition = ExponentialMovingAverageDefinition(lookback=3)

    first = compute_exponential_moving_average(definition, bars)
    second = compute_exponential_moving_average(definition, bars)

    assert first == second


def test_repeated_calculation_produces_identical_decimal_values() -> None:
    bars = _series("100.111", "102.222", "104.333", "106.444")
    definition = ExponentialMovingAverageDefinition(lookback=2)

    first = compute_exponential_moving_average(definition, bars)
    second = compute_exponential_moving_average(definition, bars)

    assert [v.value for v in first] == [v.value for v in second]
    for value in first:
        assert isinstance(value.value, Decimal)


# ---------------------------------------------------------------------------
# Mathematical invariants over monotonic / constant series
# ---------------------------------------------------------------------------


def test_constant_price_series_ema_remains_constant() -> None:
    bars = _series("50", "50", "50", "50", "50", "50")
    definition = ExponentialMovingAverageDefinition(lookback=3)

    values = compute_exponential_moving_average(definition, bars)

    assert all(v.value == Decimal("50") for v in values)


def test_monotonically_increasing_closes_produces_deterministic_increasing_ema() -> None:
    bars = _series("10", "20", "30", "40", "50", "60")
    definition = ExponentialMovingAverageDefinition(lookback=3)

    values = compute_exponential_moving_average(definition, bars)

    # An EMA tracking a strictly increasing input series is itself
    # strictly increasing once past the seed (no false invariant is
    # assumed beyond this - e.g. it is NOT asserted to stay within any
    # arbitrary historical min/max band).
    for previous, current in zip(values, values[1:], strict=False):
        assert current.value > previous.value


def test_monotonically_decreasing_closes_produces_deterministic_decreasing_ema() -> None:
    bars = _series("60", "50", "40", "30", "20", "10")
    definition = ExponentialMovingAverageDefinition(lookback=3)

    values = compute_exponential_moving_average(definition, bars)

    for previous, current in zip(values, values[1:], strict=False):
        assert current.value < previous.value


@given(
    closes=st.lists(
        st.decimals(min_value="10", max_value="10000", places=2, allow_nan=False),
        min_size=1,
        max_size=25,
    ),
    lookback=st.integers(min_value=1, max_value=10),
)
def test_every_post_seed_value_satisfies_the_documented_recurrence(
    closes: list[Decimal], lookback: int
) -> None:
    bars = tuple(_bar(str(close), offset_minutes=i) for i, close in enumerate(closes))
    definition = ExponentialMovingAverageDefinition(lookback=lookback)
    alpha = Decimal(2) / Decimal(lookback + 1)

    values = compute_exponential_moving_average(definition, bars)

    if not values:
        return
    # Seed check: first value is the mean of the first `lookback` closes.
    assert values[0].value == sum(closes[:lookback], Decimal(0)) / lookback
    assert values[0].timestamp == bars[lookback - 1].timestamp

    # Recurrence check for every value after the seed.
    for index in range(1, len(values)):
        expected_bar = bars[lookback - 1 + index]
        expected = alpha * expected_bar.close + (Decimal(1) - alpha) * values[index - 1].value
        assert values[index].value == expected


@given(
    lookback=st.integers(min_value=1, max_value=8),
    extra=st.integers(min_value=0, max_value=5),
)
def test_first_valid_ema_occurs_exactly_at_the_documented_warm_up_point(
    lookback: int, extra: int
) -> None:
    bars = tuple(_bar(str(100 + i), offset_minutes=i) for i in range(lookback + extra))
    definition = ExponentialMovingAverageDefinition(lookback=lookback)

    values = compute_exponential_moving_average(definition, bars)

    assert len(values) == extra + 1
    assert values[0].timestamp == bars[lookback - 1].timestamp


# ---------------------------------------------------------------------------
# Application layer integration is covered by
# tests/unit/application/services/test_feature_engine_service.py
# (exponential_moving_average() tests).
# ---------------------------------------------------------------------------
