# tests/unit/signal_intelligence/feature_engine/test_atr.py
#
# Unit tests for the Checkpoint 17 ATR computation - pure Python, no
# database, no Django, runs unconditionally.
from __future__ import annotations

from datetime import UTC, datetime, timedelta
from decimal import Decimal

import pytest
from hypothesis import given
from hypothesis import strategies as st

from intraday.domain.instrument.contracts import make_instrument_id
from intraday.domain.market_data.contracts import Bar
from intraday.domain.market_data.quality import DuplicateBarTimestampError, OutOfOrderBarError
from intraday.domain.shared_kernel.contracts import Exchange, InstrumentId, Timeframe
from intraday.signal_intelligence.feature_engine.atr import compute_average_true_range
from intraday.signal_intelligence.feature_engine.definitions import (
    AverageTrueRangeDefinition,
)
from intraday.signal_intelligence.feature_engine.errors import (
    InvalidLookbackError,
    MixedInstrumentSeriesError,
    MixedTimeframeSeriesError,
)

RELIANCE = make_instrument_id(Exchange.NSE, "RELIANCE")
TCS = make_instrument_id(Exchange.NSE, "TCS")
START = datetime(2026, 1, 1, 3, 50, tzinfo=UTC)


def _ohlc_bar(
    *,
    open_: str,
    high: str,
    low: str,
    close: str,
    offset_minutes: int = 0,
    instrument_id: InstrumentId = RELIANCE,
    timeframe: Timeframe = Timeframe.FIVE_MINUTE,
) -> Bar:
    return Bar(
        instrument_id=instrument_id,
        timeframe=timeframe,
        timestamp=START + timedelta(minutes=5 * offset_minutes),
        open=Decimal(open_),
        high=Decimal(high),
        low=Decimal(low),
        close=Decimal(close),
        volume=Decimal("1000"),
    )


def _flat_bar(price: str, *, offset_minutes: int = 0) -> Bar:
    """A bar whose open/high/low/close are all identical - the smallest
    valid Bar (`low <= open,close <= high` trivially holds when all four
    are equal)."""
    return _ohlc_bar(open_=price, high=price, low=price, close=price, offset_minutes=offset_minutes)


# ---------------------------------------------------------------------------
# Feature identity
# ---------------------------------------------------------------------------


def test_atr_5_and_atr_10_have_distinct_identity() -> None:
    atr5 = AverageTrueRangeDefinition(lookback=5)
    atr10 = AverageTrueRangeDefinition(lookback=10)
    assert atr5.feature_name != atr10.feature_name
    assert atr5.feature_name == "atr_5"
    assert atr10.feature_name == "atr_10"


def test_same_definition_produces_equal_identity() -> None:
    a = AverageTrueRangeDefinition(lookback=14)
    b = AverageTrueRangeDefinition(lookback=14)
    assert a == b
    assert a.feature_name == b.feature_name
    assert a.feature_version == b.feature_version


@pytest.mark.parametrize("invalid_lookback", [0, -1, -5])
def test_invalid_lookback_rejected(invalid_lookback: int) -> None:
    with pytest.raises(InvalidLookbackError):
        AverageTrueRangeDefinition(lookback=invalid_lookback)


def test_non_integer_lookback_rejected() -> None:
    with pytest.raises(InvalidLookbackError):
        AverageTrueRangeDefinition(lookback=5.5)  # type: ignore[arg-type]


def test_bool_lookback_rejected() -> None:
    with pytest.raises(InvalidLookbackError):
        AverageTrueRangeDefinition(lookback=True)  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# Calculation - independently hand-derived test vector (Checkpoint 17 §14)
#
#   lookback N = 3
#   bar0: O=9  H=10 L=8  C=9                (supplies only the initial
#                                             previous close - produces
#                                             no TR/ATR of its own)
#   bar1: O=10 H=11 L=9  C=10 -> TR1 = max(11-9=2, |11-9|=2, |9-9|=0) = 2
#   bar2: O=11 H=12 L=10 C=11 -> TR2 = max(12-10=2, |12-10|=2, |10-10|=0) = 2
#   bar3: O=12 H=13 L=11 C=12 -> TR3 = max(13-11=2, |13-11|=2, |11-11|=0) = 2
#   seed ATR (mean of TR1..TR3) = 2, at bar3's own timestamp
#   bar4: O=13 H=14 L=9  C=13 -> TR4 = max(14-9=5, |14-12|=2, |9-12|=3) = 5
#         (previous close is bar3's close = 12)
#   ATR4 = ((2 * (3-1)) + 5) / 3 = (4 + 5) / 3 = 3
#
#   expected ATR(3) series: 2, 3
#
# Derived independently of the implementation under test (by hand, per
# the documented Wilder seed/recurrence rule) - not generated by calling
# compute_average_true_range itself.
# ---------------------------------------------------------------------------


def test_known_3_period_atr_manually_derived_vector() -> None:
    bars = (
        _ohlc_bar(open_="9", high="10", low="8", close="9", offset_minutes=0),
        _ohlc_bar(open_="10", high="11", low="9", close="10", offset_minutes=1),
        _ohlc_bar(open_="11", high="12", low="10", close="11", offset_minutes=2),
        _ohlc_bar(open_="12", high="13", low="11", close="12", offset_minutes=3),
        _ohlc_bar(open_="13", high="14", low="9", close="13", offset_minutes=4),
    )
    definition = AverageTrueRangeDefinition(lookback=3)

    values = compute_average_true_range(definition, bars)

    assert [v.value for v in values] == [Decimal("2"), Decimal("3")]
    assert values[0].timestamp == bars[3].timestamp
    assert values[1].timestamp == bars[4].timestamp


def test_decimal_precision_preserved_not_float() -> None:
    bars = tuple(_flat_bar("100.01", offset_minutes=i) for i in range(4))
    definition = AverageTrueRangeDefinition(lookback=3)

    values = compute_average_true_range(definition, bars)

    assert len(values) == 1
    assert isinstance(values[0].value, Decimal)


def test_all_output_values_are_decimal() -> None:
    bars = (
        _ohlc_bar(open_="9", high="10", low="8", close="9", offset_minutes=0),
        _ohlc_bar(open_="10", high="11", low="9", close="10", offset_minutes=1),
        _ohlc_bar(open_="11", high="12", low="10", close="11", offset_minutes=2),
        _ohlc_bar(open_="12", high="13", low="11", close="12", offset_minutes=3),
    )
    definition = AverageTrueRangeDefinition(lookback=3)

    values = compute_average_true_range(definition, bars)

    for value in values:
        assert isinstance(value.value, Decimal)


def test_output_is_chronologically_ordered() -> None:
    bars = tuple(_flat_bar(str(100 + i), offset_minutes=i) for i in range(6))
    definition = AverageTrueRangeDefinition(lookback=2)

    values = compute_average_true_range(definition, bars)

    timestamps = [v.timestamp for v in values]
    assert timestamps == sorted(timestamps)


# ---------------------------------------------------------------------------
# True Range correctness - gap test (Checkpoint 17 §16)
#
# Proves True Range is NOT simply high-low: a gap where the previous
# close differs materially from the current high/low must dominate the
# calculation.
# ---------------------------------------------------------------------------


def test_true_range_captures_a_gap_not_just_high_minus_low() -> None:
    # previous bar closes at 100; current bar gaps up, trading only 104-105
    # (a narrow 1-point range) - the gap itself (5 points) must dominate.
    previous = _ohlc_bar(open_="99", high="101", low="98", close="100", offset_minutes=0)
    current = _ohlc_bar(open_="104.5", high="105", low="104", close="104.8", offset_minutes=1)
    bars = (previous, current)

    # lookback=1 so the very first TR value (bar index 1) becomes the ATR
    # seed directly - isolates the TR calculation from any smoothing.
    definition = AverageTrueRangeDefinition(lookback=1)

    values = compute_average_true_range(definition, bars)

    # high-low alone would be 105-104=1; the gap-aware TR must be 5
    # (|105 - 100|).
    assert values[0].value == Decimal("5")


# ---------------------------------------------------------------------------
# Constant market test (Checkpoint 17 §15)
# ---------------------------------------------------------------------------


def test_constant_ohlc_series_produces_zero_atr() -> None:
    bars = tuple(_flat_bar("100", offset_minutes=i) for i in range(6))
    definition = AverageTrueRangeDefinition(lookback=3)

    values = compute_average_true_range(definition, bars)

    assert all(v.value == Decimal("0") for v in values)


# ---------------------------------------------------------------------------
# First-bar policy / warm-up (Checkpoint 17 §3, §12)
# ---------------------------------------------------------------------------


def test_zero_bars_produces_no_values() -> None:
    definition = AverageTrueRangeDefinition(lookback=5)
    assert compute_average_true_range(definition, ()) == ()


def test_single_bar_produces_no_values_because_it_has_no_previous_close() -> None:
    bars = (_flat_bar("100"),)
    definition = AverageTrueRangeDefinition(lookback=1)
    assert compute_average_true_range(definition, bars) == ()


def test_exactly_n_plus_one_bars_produces_exactly_one_seed_value() -> None:
    # lookback=3 needs 3 TR observations, which needs 4 bars total.
    bars = tuple(_flat_bar(str(100 + i), offset_minutes=i) for i in range(4))
    definition = AverageTrueRangeDefinition(lookback=3)

    values = compute_average_true_range(definition, bars)

    assert len(values) == 1


def test_n_bars_only_produces_no_values_one_short_of_seed() -> None:
    # lookback=3 needs 4 bars; 3 bars is one short.
    bars = tuple(_flat_bar(str(100 + i), offset_minutes=i) for i in range(3))
    definition = AverageTrueRangeDefinition(lookback=3)

    assert compute_average_true_range(definition, bars) == ()


def test_n_plus_two_bars_produces_exactly_two_values() -> None:
    bars = tuple(_flat_bar(str(100 + i), offset_minutes=i) for i in range(5))
    definition = AverageTrueRangeDefinition(lookback=3)

    values = compute_average_true_range(definition, bars)

    assert len(values) == 2


def test_first_valid_timestamp_is_the_bar_completing_the_seed_window() -> None:
    bars = tuple(_flat_bar(str(100 + i), offset_minutes=i) for i in range(4))
    definition = AverageTrueRangeDefinition(lookback=3)

    values = compute_average_true_range(definition, bars)

    # bars[0] supplies only the initial previous close; TR1..TR3 come
    # from bars[1..3], so the seed timestamp is bars[3]'s own timestamp.
    assert values[0].timestamp == bars[3].timestamp


# ---------------------------------------------------------------------------
# Wilder recurrence
# ---------------------------------------------------------------------------


def test_wilder_recurrence_holds_for_every_post_seed_value() -> None:
    bars = tuple(_flat_bar(str(100 + (i % 3)), offset_minutes=i) for i in range(8))
    definition = AverageTrueRangeDefinition(lookback=3)

    values = compute_average_true_range(definition, bars)

    n = Decimal(3)
    n_minus_1 = Decimal(2)
    true_ranges = [
        max(cur.high - cur.low, abs(cur.high - prev.close), abs(cur.low - prev.close))
        for prev, cur in zip(bars, bars[1:], strict=False)
    ]
    post_seed_trs = true_ranges[definition.lookback :]
    for previous_value, current_value, tr in zip(values, values[1:], post_seed_trs, strict=False):
        expected = ((previous_value.value * n_minus_1) + tr) / n
        assert current_value.value == expected


# ---------------------------------------------------------------------------
# Look-ahead safety
# ---------------------------------------------------------------------------


def test_future_bar_does_not_influence_earlier_output() -> None:
    short_series = tuple(_flat_bar(str(100 + i), offset_minutes=i) for i in range(4))
    longer_series = short_series + (_flat_bar("999", offset_minutes=4),)
    definition = AverageTrueRangeDefinition(lookback=3)

    short_values = compute_average_true_range(definition, short_series)
    longer_values = compute_average_true_range(definition, longer_series)

    assert short_values[0] == longer_values[0]


def test_modifying_a_future_bar_does_not_change_earlier_atr_values() -> None:
    definition = AverageTrueRangeDefinition(lookback=2)
    base = tuple(_flat_bar(str(100 + i), offset_minutes=i) for i in range(4))
    variant_a = base + (_flat_bar("200", offset_minutes=4),)
    variant_b = base + (_flat_bar("9999", offset_minutes=4),)

    values_a = compute_average_true_range(definition, variant_a)
    values_b = compute_average_true_range(definition, variant_b)

    assert values_a[:-1] == values_b[:-1]


@given(
    prices=st.lists(
        st.decimals(min_value="10", max_value="1000", places=2, allow_nan=False),
        min_size=2,
        max_size=20,
    ),
    lookback=st.integers(min_value=1, max_value=8),
)
def test_no_output_uses_future_observations(prices: list[Decimal], lookback: int) -> None:
    full_bars = tuple(_flat_bar(str(price), offset_minutes=i) for i, price in enumerate(prices))
    prefix_bars = full_bars[:-1]
    definition = AverageTrueRangeDefinition(lookback=lookback)

    full_values = compute_average_true_range(definition, full_bars)
    prefix_values = compute_average_true_range(definition, prefix_bars)

    assert prefix_values == full_values[: len(prefix_values)]


# ---------------------------------------------------------------------------
# Instrument / timeframe / chronology integrity
# ---------------------------------------------------------------------------


def test_bars_from_different_instruments_rejected() -> None:
    bars = (
        _ohlc_bar(
            open_="9", high="10", low="8", close="9", offset_minutes=0, instrument_id=RELIANCE
        ),
        _ohlc_bar(open_="10", high="11", low="9", close="10", offset_minutes=1, instrument_id=TCS),
    )
    definition = AverageTrueRangeDefinition(lookback=1)

    with pytest.raises(MixedInstrumentSeriesError):
        compute_average_true_range(definition, bars)


def test_feature_output_retains_correct_instrument_identity() -> None:
    bars = tuple(_flat_bar(str(100 + i), offset_minutes=i) for i in range(4))
    definition = AverageTrueRangeDefinition(lookback=3)

    values = compute_average_true_range(definition, bars)

    assert values[0].instrument_id == RELIANCE


def test_timeframe_is_retained_on_output() -> None:
    bars = tuple(_flat_bar(str(100 + i), offset_minutes=i) for i in range(4))
    definition = AverageTrueRangeDefinition(lookback=3)

    values = compute_average_true_range(definition, bars)

    assert values[0].timeframe == Timeframe.FIVE_MINUTE


def test_mixed_timeframe_input_rejected() -> None:
    bars = (
        _ohlc_bar(
            open_="9",
            high="10",
            low="8",
            close="9",
            offset_minutes=0,
            timeframe=Timeframe.FIVE_MINUTE,
        ),
        _ohlc_bar(
            open_="10",
            high="11",
            low="9",
            close="10",
            offset_minutes=1,
            timeframe=Timeframe.ONE_MINUTE,
        ),
    )
    definition = AverageTrueRangeDefinition(lookback=1)

    with pytest.raises(MixedTimeframeSeriesError):
        compute_average_true_range(definition, bars)


def test_duplicate_bar_timestamps_rejected() -> None:
    duplicate = _flat_bar("100", offset_minutes=0)
    bars = (duplicate, duplicate)
    definition = AverageTrueRangeDefinition(lookback=1)

    with pytest.raises(DuplicateBarTimestampError):
        compute_average_true_range(definition, bars)


def test_out_of_order_bars_rejected() -> None:
    bars = (_flat_bar("100", offset_minutes=1), _flat_bar("101", offset_minutes=0))
    definition = AverageTrueRangeDefinition(lookback=1)

    with pytest.raises(OutOfOrderBarError):
        compute_average_true_range(definition, bars)


# ---------------------------------------------------------------------------
# Determinism
# ---------------------------------------------------------------------------


def test_same_input_produces_identical_output() -> None:
    bars = tuple(_flat_bar(str(100 + i), offset_minutes=i) for i in range(6))
    definition = AverageTrueRangeDefinition(lookback=3)

    first = compute_average_true_range(definition, bars)
    second = compute_average_true_range(definition, bars)

    assert first == second


def test_repeated_calculation_produces_identical_decimal_values() -> None:
    bars = tuple(_flat_bar(str(100.111 + i), offset_minutes=i) for i in range(5))
    definition = AverageTrueRangeDefinition(lookback=2)

    first = compute_average_true_range(definition, bars)
    second = compute_average_true_range(definition, bars)

    assert [v.value for v in first] == [v.value for v in second]


# ---------------------------------------------------------------------------
# Property-based testing
# ---------------------------------------------------------------------------


@given(
    prices=st.lists(
        st.decimals(min_value="10", max_value="1000", places=2, allow_nan=False),
        min_size=1,
        max_size=20,
    ),
)
def test_true_range_formula_matches_canonical_definition(prices: list[Decimal]) -> None:
    bars = tuple(_flat_bar(str(price), offset_minutes=i) for i, price in enumerate(prices))
    definition = AverageTrueRangeDefinition(lookback=1)

    values = compute_average_true_range(definition, bars)

    for index, value in enumerate(values):
        previous_bar = bars[index]
        current_bar = bars[index + 1]
        expected_tr = max(
            current_bar.high - current_bar.low,
            abs(current_bar.high - previous_bar.close),
            abs(current_bar.low - previous_bar.close),
        )
        assert value.value == expected_tr


@given(
    prices=st.lists(
        st.decimals(min_value="10", max_value="1000", places=2, allow_nan=False),
        min_size=1,
        max_size=20,
    ),
    lookback=st.integers(min_value=1, max_value=6),
)
def test_wilder_recurrence_property(prices: list[Decimal], lookback: int) -> None:
    bars = tuple(_flat_bar(str(price), offset_minutes=i) for i, price in enumerate(prices))
    definition = AverageTrueRangeDefinition(lookback=lookback)

    values = compute_average_true_range(definition, bars)
    if not values:
        return

    true_ranges = [
        max(cur.high - cur.low, abs(cur.high - prev.close), abs(cur.low - prev.close))
        for prev, cur in zip(bars, bars[1:], strict=False)
    ]

    # Seed check.
    seed_window = true_ranges[:lookback]
    assert values[0].value == sum(seed_window, Decimal(0)) / lookback

    # Recurrence check for every post-seed value.
    n = Decimal(lookback)
    n_minus_1 = Decimal(lookback - 1)
    for index in range(1, len(values)):
        tr = true_ranges[lookback + index - 1]
        expected = ((values[index - 1].value * n_minus_1) + tr) / n
        assert values[index].value == expected


@given(
    lookback=st.integers(min_value=1, max_value=6),
    extra_bars=st.integers(min_value=0, max_value=5),
)
def test_warm_up_boundary_is_deterministic(lookback: int, extra_bars: int) -> None:
    total_bars = lookback + 1 + extra_bars
    bars = tuple(_flat_bar(str(100 + i), offset_minutes=i) for i in range(total_bars))
    definition = AverageTrueRangeDefinition(lookback=lookback)

    values = compute_average_true_range(definition, bars)

    assert len(values) == extra_bars + 1
    assert values[0].timestamp == bars[lookback].timestamp
