# File: src/intraday/domain/market_data/provenance.py
#
# Checkpoint 65.12: the additive per-provider provenance vocabulary
# designed (but not implemented) by 65.01, and implemented here exactly
# as designed there — replacing nothing, deleting nothing, relabeling
# nothing.
#
# WHY THIS EXISTS: `HistoricalBar.source` (see `infrastructure.
# persistence.models`) has always meant "which pipeline STAGE wrote
# this row" (`"API_FETCH"` for every row, synthetic or not — see
# `application.services.historical_data_preparation.
# PROVENANCE_API_FETCH`). It has never meant "is this row genuine NSE
# market data". Overloading one field for both questions is exactly
# the ambiguity 65.00/65.01/65.11 all found: 5,100 `HistoricalBar` rows
# are ALL labelled `source="API_FETCH"` regardless of whether they came
# from `SyntheticHistoricalBarProvider` (a deterministic hash-seeded
# generator, see `infrastructure.market_data_providers.
# synthetic_historical`) or from a genuine external source.
#
# `HistoricalBar.provenance` (migration 0036, purely additive — see
# that migration's own docstring) is the answer: a SECOND, EXPLICIT,
# per-row field naming what KIND of data the row's OHLCV values
# actually are, orthogonal to `source`'s "which stage wrote it".
#
# The three states are intentionally exhaustive and mutually
# exclusive — a row is always in exactly one:
PROVENANCE_REAL_DHAN = "REAL_DHAN"
"""Genuinely observed NSE/BSE market data, ingested from Dhan (live
quote polling aggregated into bars, or — once built — a real Dhan
historical-candle REST adapter). No provider that emits this label
exists yet as of 65.12; the constant exists so that the day a real
adapter is built, it has an unambiguous label to stamp rather than a
new ad-hoc string being invented at that point."""

PROVENANCE_SYNTHETIC_TEST = "SYNTHETIC_TEST"
"""Deterministically generated by `SyntheticHistoricalBarProvider` (or
any future fixture/test provider) — never real price action, safe for
engine-correctness tests (as 65.11 legitimately used it), NEVER safe as
research evidence."""

PROVENANCE_UNKNOWN = "UNKNOWN"
"""No corroborating evidence either way. This is the ONLY default a
migration or a provider that declares nothing is allowed to assign —
never upgraded to REAL_DHAN without positive evidence, per this
checkpoint's hard rule. This is the state of all 5,100 pre-65.12
`HistoricalBar` rows immediately after migration 0036 runs, and stays
the state of any of them formula-replay cannot positively attribute to
`SyntheticHistoricalBarProvider`."""

PROVENANCE_CHOICES = (
    PROVENANCE_REAL_DHAN,
    PROVENANCE_SYNTHETIC_TEST,
    PROVENANCE_UNKNOWN,
)


def is_research_eligible(provenance: str) -> bool:
    """A single, explicit, honest answer to "can this bar be used for
    research?" — the Part B requirement. Only `PROVENANCE_REAL_DHAN`
    rows qualify; `SYNTHETIC_TEST` and `UNKNOWN` are both excluded
    (Part G: unverifiable data must never silently become research
    evidence, exactly like data known to be fake)."""
    return provenance == PROVENANCE_REAL_DHAN


__all__ = [
    "PROVENANCE_REAL_DHAN",
    "PROVENANCE_SYNTHETIC_TEST",
    "PROVENANCE_UNKNOWN",
    "PROVENANCE_CHOICES",
    "is_research_eligible",
]
